name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lighthouse CI on docs/
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true

  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lychee Broken Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose ./docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  htmlvalidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HTML5 Validator
        uses: chabad360/html5validator-action@v1
        with:
          root: docs

